import React from "react";
import { ParallaxScroll } from "@/components/ui/parallax-scroll";

export default function index() {
  return (
    <>
      <ParallaxScroll images={images} />
    </>
  );
}

const images = [
  "https://mochrks.github.io/assets/img-photo/ig1.jpg",
  "https://mochrks.github.io/assets/img-photo/ig2.jpg",
  "https://mochrks.github.io/assets/img-photo/ig3.jpg",
  "https://mochrks.github.io/assets/img-photo/ig4.jpg",
  "https://mochrks.github.io/assets/img-photo/ig5.jpg",
  "https://mochrks.github.io/assets/img-photo/ig6.jpg",
  "https://mochrks.github.io/assets/img-photo/ig7.jpg",
  "https://mochrks.github.io/assets/img-photo/ig8.jpg",
  "https://mochrks.github.io/assets/img-photo/ig9.jpg",
  "https://mochrks.github.io/assets/img-photo/ig10.jpg",
  "https://mochrks.github.io/assets/img-photo/ig11.jpg",
  "https://mochrks.github.io/assets/img-photo/ig12.jpg",
  "https://mochrks.github.io/assets/img-photo/ig13.jpg",
  "https://mochrks.github.io/assets/img-photo/ig14.jpg",
  "https://mochrks.github.io/assets/img-photo/ig15.jpg",
  "https://mochrks.github.io/assets/img-photo/ig16.jpg",
  "https://mochrks.github.io/assets/img-photo/ig17.jpg",
  "https://mochrks.github.io/assets/img-photo/ig18.jpg",
  "https://mochrks.github.io/assets/img-photo/ig19.jpg",
  "https://mochrks.github.io/assets/img-photo/ig20.jpg",
  "https://mochrks.github.io/assets/img-photo/ig21.jpg",
  "https://mochrks.github.io/assets/img-photo/ig22.jpg",
  "https://mochrks.github.io/assets/img-photo/ig23.jpg",
  "https://mochrks.github.io/assets/img-photo/ig24.jpg",
  "https://mochrks.github.io/assets/img-photo/ig25.jpg",
  "https://mochrks.github.io/assets/img-photo/ig26.jpg",
  "https://mochrks.github.io/assets/img-photo/ig27.jpg",
  "https://mochrks.github.io/assets/img-photo/ig28.jpg",
  "https://mochrks.github.io/assets/img-photo/ig29.jpg",
  "https://mochrks.github.io/assets/img-photo/ig30.jpg",
  "https://mochrks.github.io/assets/img-photo/ig31.jpg",
  "https://mochrks.github.io/assets/img-photo/ig32.jpg",
  "https://mochrks.github.io/assets/img-photo/1.jpg",
  "https://mochrks.github.io/assets/img-photo/2.jpg",
  "https://mochrks.github.io/assets/img-photo/3.jpg",
  "https://mochrks.github.io/assets/img-photo/4.jpg",
  "https://mochrks.github.io/assets/img-photo/4.jpeg",
  "https://mochrks.github.io/assets/img-photo/5.jpg",
  "https://mochrks.github.io/assets/img-photo/10.jpeg",
  "https://mochrks.github.io/assets/img-photo/11.png",
  "https://mochrks.github.io/assets/img-photo/12.png",
  "https://mochrks.github.io/assets/img-photo/13.png",
  "https://mochrks.github.io/assets/img-photo/14.jpeg",
  "https://mochrks.github.io/assets/img-photo/15.png",
  "https://mochrks.github.io/assets/img-photo/16.png",
  "https://mochrks.github.io/assets/img-photo/17.png",
  "https://mochrks.github.io/assets/img-photo/18.jpg",
  "https://mochrks.github.io/assets/img-photo/19.jpg",
  "https://mochrks.github.io/assets/img-photo/19.png",
  "https://mochrks.github.io/assets/img-photo/21.png",
  "https://mochrks.github.io/assets/img-photo/22.jpg",
  "https://mochrks.github.io/assets/img-photo/23.jpg",
  "https://mochrks.github.io/assets/img-photo/24.jpeg",
  "https://mochrks.github.io/assets/img-photo/25.jpeg",
  "https://mochrks.github.io/assets/img-photo/26.png",
  "https://mochrks.github.io/assets/img-photo/27.jpeg",
  "https://mochrks.github.io/assets/img-photo/28.jpeg",
  "https://mochrks.github.io/assets/img-photo/29.jpeg",
  "https://mochrks.github.io/assets/img-photo/30.jpeg",
  "https://mochrks.github.io/assets/img-photo/31.jpeg",
  "https://mochrks.github.io/assets/img-photo/32.jpeg",
  "https://mochrks.github.io/assets/img-photo/17.png",
  "https://mochrks.github.io/assets/img-photo/1.jpg",

];
