export const SPOTIFY_ENDPOINTS = {
  TOKEN: import.meta.env.VITE_SPOTIFY_TOKEN_ENDPOINT,
  NOW_PLAYING: import.meta.env.VITE_SPOTIFY_NOW_PLAYING_ENDPOINT,
  RECENTLY_PLAYED: import.meta.env.VITE_SPOTIFY_RECENTLY_PLAYED_ENDPOINT,
  USER: import.meta.env.VITE_SPOTIFY_USER_ENDPOINT,
};
