import { Artwork } from "@/types/design-page";

export const artworks: Artwork[] = [
  {
    id: 1,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-1.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 2,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-10.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 3,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-100.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 4,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-101.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 5,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-102.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 6,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-103.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 7,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-104.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 8,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-105.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 9,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-106.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 10,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-107.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 11,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-108.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 12,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-109.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 13,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-11.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 14,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-12.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 15,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-13.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 16,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-14.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 17,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-15.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 18,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-16.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 19,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-17.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 20,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-18.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 21,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-19.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 22,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-2.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 23,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-20.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 24,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-21.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 25,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-22.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 26,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-23.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 27,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-24.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 28,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-25.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 29,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-26.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 30,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-27.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 31,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-28.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 32,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-29.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 33,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-3.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 34,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-30.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 35,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-31.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 36,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-32.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 37,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-33.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 38,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-34.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 39,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-35.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 40,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-36.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 41,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-37.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 42,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-38.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 43,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-39.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 44,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-4.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 45,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-40.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 46,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-41.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 47,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-42.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 48,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-43.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 49,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-44.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 50,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-45.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 51,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-46.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 52,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-47.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 53,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-48.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 54,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-49.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 55,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-5.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 56,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-50.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 57,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-51.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 58,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-52.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 59,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-53.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 60,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-54.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 61,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-55.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 62,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-56.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 63,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-57.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 64,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-58.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 65,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-59.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 66,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-6.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 67,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-60.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 68,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-61.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 69,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-62.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 70,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-63.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 71,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-64.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 72,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-65.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 73,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-66.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 74,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-67.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 75,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-68.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 76,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-69.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 77,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-7.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 78,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-70.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 79,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-71.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 80,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-72.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 81,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-73.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 82,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-74.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 83,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-75.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 84,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-76.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 85,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-77.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 86,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-78.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 87,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-79.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 88,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-8.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 89,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-80.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 90,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-81.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 91,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-82.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 92,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-83.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 93,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-84.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 94,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-85.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 95,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-86.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 96,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-87.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 97,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-88.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 98,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-89.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 99,
    title: "Digital Artwork",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-9.webp",
    artist: "@mochrks",
    description:
      "A creative digital artwork blending reality and imagination into a unique visual experience.",
    category: "artwork",
  },
  {
    id: 100,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-90.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 101,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-91.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 102,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-92.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 103,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-93.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 104,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-94.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 105,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-95.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 106,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-96.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 107,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-97.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 108,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-98.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
  {
    id: 109,
    title: "Design",
    imageUrl: "https://mochrks.github.io/assets/artwork/artwork-99.webp",
    artist: "@mochrks",
    description: "A meticulously crafted design showcasing creativity and attention to detail.",
    category: "design",
  },
];
