import { Artwork } from "@/types/design-page";

export const images: Artwork[] = [
  {
    id: 1,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-1.jpg",
    artist: "@mochrks",
    description: "Mesmerizing image revealing hidden details.",
    category: "photo",
  },
  {
    id: 2,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-2.jpg",
    artist: "@mochrks",
    description: "Expressive portrait evoking strong emotions.",
    category: "photo",
  },
  {
    id: 3,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-3.jpg",
    artist: "@mochrks",
    description: "Moody photograph revealing hidden details.",
    category: "photo",
  },
  {
    id: 4,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-4.jpg",
    artist: "@mochrks",
    description: "Serene macro shot freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 5,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-5.jpg",
    artist: "@mochrks",
    description: "Stunning macro shot captured during the golden hour.",
    category: "photo",
  },
  {
    id: 6,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-6.jpg",
    artist: "@mochrks",
    description: "Authentic landscape preserving memories.",
    category: "photo",
  },
  {
    id: 7,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-7.jpg",
    artist: "@mochrks",
    description: "Dramatic macro shot freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 8,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-8.jpg",
    artist: "@mochrks",
    description: "Intimate scene highlighting natural light.",
    category: "photo",
  },
  {
    id: 9,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-9.jpg",
    artist: "@mochrks",
    description: "Expressive macro shot captured during the golden hour.",
    category: "photo",
  },
  {
    id: 10,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-10.jpg",
    artist: "@mochrks",
    description: "Captivating capture revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 11,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-11.jpg",
    artist: "@mochrks",
    description: "Beautifully composed portrait telling a unique story.",
    category: "photo",
  },
  {
    id: 12,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-12.jpg",
    artist: "@mochrks",
    description: "Artistic photographic shot creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 13,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-13.jpg",
    artist: "@mochrks",
    description: "Beautifully composed perspective exploring leading lines.",
    category: "photo",
  },
  {
    id: 14,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-14.jpg",
    artist: "@mochrks",
    description: "Moody image telling a unique story.",
    category: "photo",
  },
  {
    id: 15,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-15.jpg",
    artist: "@mochrks",
    description: "Serene capture captured during the golden hour.",
    category: "photo",
  },
  {
    id: 16,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-16.jpg",
    artist: "@mochrks",
    description: "Candid portrait evoking strong emotions.",
    category: "photo",
  },
  {
    id: 17,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-17.jpg",
    artist: "@mochrks",
    description: "Vibrant panorama revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 18,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-18.jpg",
    artist: "@mochrks",
    description: "Poignant visual playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 19,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-19.jpg",
    artist: "@mochrks",
    description: "Picturesque landscape preserving memories.",
    category: "photo",
  },
  {
    id: 20,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-20.jpg",
    artist: "@mochrks",
    description: "Raw landscape preserving memories.",
    category: "photo",
  },
  {
    id: 21,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-21.jpg",
    artist: "@mochrks",
    description: "Nostalgic perspective creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 22,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-22.jpg",
    artist: "@mochrks",
    description: "Stunning capture highlighting natural light.",
    category: "photo",
  },
  {
    id: 23,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-23.jpg",
    artist: "@mochrks",
    description: "Intimate macro shot revealing hidden details.",
    category: "photo",
  },
  {
    id: 24,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-24.jpg",
    artist: "@mochrks",
    description: "Stunning portrait revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 25,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-25.jpg",
    artist: "@mochrks",
    description: "Vivid exposure telling a unique story.",
    category: "photo",
  },
  {
    id: 26,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-26.jpg",
    artist: "@mochrks",
    description: "Timeless snapshot documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 27,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-27.jpg",
    artist: "@mochrks",
    description: "Ethereal portrait focusing on symmetry.",
    category: "photo",
  },
  {
    id: 28,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-28.jpg",
    artist: "@mochrks",
    description: "Nostalgic photograph preserving memories.",
    category: "photo",
  },
  {
    id: 29,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-29.jpg",
    artist: "@mochrks",
    description: "Vibrant snapshot showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 30,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-30.jpg",
    artist: "@mochrks",
    description: "Beautifully composed street photography showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 31,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-31.jpg",
    artist: "@mochrks",
    description: "Vibrant frame preserving memories.",
    category: "photo",
  },
  {
    id: 32,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-32.jpg",
    artist: "@mochrks",
    description: "Cinematic photograph highlighting natural light.",
    category: "photo",
  },
  {
    id: 33,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-33.jpg",
    artist: "@mochrks",
    description: "Dramatic photographic shot bringing the subject to life.",
    category: "photo",
  },
  {
    id: 34,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-34.jpg",
    artist: "@mochrks",
    description: "Serene photo exploring leading lines.",
    category: "photo",
  },
  {
    id: 35,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-35.jpg",
    artist: "@mochrks",
    description: "Timeless composition highlighting natural light.",
    category: "photo",
  },
  {
    id: 36,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-36.jpg",
    artist: "@mochrks",
    description: "Cinematic visual capturing true personality.",
    category: "photo",
  },
  {
    id: 37,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-37.jpg",
    artist: "@mochrks",
    description: "Vivid panorama exploring leading lines.",
    category: "photo",
  },
  {
    id: 38,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-38.jpg",
    artist: "@mochrks",
    description: "Majestic panorama revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 39,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-39.jpg",
    artist: "@mochrks",
    description: "Ethereal capture freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 40,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-40.jpg",
    artist: "@mochrks",
    description: "Candid landscape documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 41,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-41.jpg",
    artist: "@mochrks",
    description: "Cinematic street photography preserving memories.",
    category: "photo",
  },
  {
    id: 42,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-42.jpg",
    artist: "@mochrks",
    description: "Poignant photographic shot documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 43,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-43.jpg",
    artist: "@mochrks",
    description: "Timeless moment telling a unique story.",
    category: "photo",
  },
  {
    id: 44,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-44.jpg",
    artist: "@mochrks",
    description: "Candid composition revealing hidden details.",
    category: "photo",
  },
  {
    id: 45,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-45.jpg",
    artist: "@mochrks",
    description: "Powerful moment creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 46,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-46.jpg",
    artist: "@mochrks",
    description: "Raw moment showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 47,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-47.jpg",
    artist: "@mochrks",
    description: "Powerful visual revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 48,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-48.jpg",
    artist: "@mochrks",
    description: "Vivid capture revealing hidden details.",
    category: "photo",
  },
  {
    id: 49,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-49.jpg",
    artist: "@mochrks",
    description: "Poignant frame capturing true personality.",
    category: "photo",
  },
  {
    id: 50,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-50.jpg",
    artist: "@mochrks",
    description: "Vivid image documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 51,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-51.jpg",
    artist: "@mochrks",
    description: "Expressive snapshot showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 52,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-52.jpg",
    artist: "@mochrks",
    description: "Raw scene exploring leading lines.",
    category: "photo",
  },
  {
    id: 53,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-53.webp",
    artist: "@mochrks",
    description: "Dramatic street photography revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 54,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-54.webp",
    artist: "@mochrks",
    description: "Intimate exposure focusing on symmetry.",
    category: "photo",
  },
  {
    id: 55,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-55.jpg",
    artist: "@mochrks",
    description: "Moody snapshot highlighting natural light.",
    category: "photo",
  },
  {
    id: 56,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-56.jpg",
    artist: "@mochrks",
    description: "Raw perspective showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 57,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-57.jpg",
    artist: "@mochrks",
    description: "Breathtaking visual bringing the subject to life.",
    category: "photo",
  },
  {
    id: 58,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-58.jpg",
    artist: "@mochrks",
    description: "Picturesque street photography preserving memories.",
    category: "photo",
  },
  {
    id: 59,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-59.jpg",
    artist: "@mochrks",
    description: "Raw scene showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 60,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-60.jpg",
    artist: "@mochrks",
    description: "Timeless perspective captured during the golden hour.",
    category: "photo",
  },
  {
    id: 61,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-61.jpg",
    artist: "@mochrks",
    description: "Striking perspective documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 62,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-62.jpg",
    artist: "@mochrks",
    description: "Candid portrait captured during the golden hour.",
    category: "photo",
  },
  {
    id: 63,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-63.jpg",
    artist: "@mochrks",
    description: "Majestic moment showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 64,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-64.jpg",
    artist: "@mochrks",
    description: "Captivating visual showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 65,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-65.jpg",
    artist: "@mochrks",
    description: "Stunning frame revealing hidden details.",
    category: "photo",
  },
  {
    id: 66,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-66.jpg",
    artist: "@mochrks",
    description: "Authentic capture capturing true personality.",
    category: "photo",
  },
  {
    id: 67,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-67.jpg",
    artist: "@mochrks",
    description: "Beautifully composed capture showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 68,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-68.jpg",
    artist: "@mochrks",
    description: "Raw photograph capturing true personality.",
    category: "photo",
  },
  {
    id: 69,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-69.jpg",
    artist: "@mochrks",
    description: "Ethereal portrait bringing the subject to life.",
    category: "photo",
  },
  {
    id: 70,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-70.jpg",
    artist: "@mochrks",
    description: "Vibrant photographic shot evoking strong emotions.",
    category: "photo",
  },
  {
    id: 71,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-71.jpg",
    artist: "@mochrks",
    description: "Moody composition revealing hidden details.",
    category: "photo",
  },
  {
    id: 72,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-72.jpg",
    artist: "@mochrks",
    description: "Majestic street photography exploring leading lines.",
    category: "photo",
  },
  {
    id: 73,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-73.jpg",
    artist: "@mochrks",
    description: "Ethereal photograph exploring leading lines.",
    category: "photo",
  },
  {
    id: 74,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-74.jpg",
    artist: "@mochrks",
    description: "Majestic photographic shot captured during the golden hour.",
    category: "photo",
  },
  {
    id: 75,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-75.jpg",
    artist: "@mochrks",
    description: "Energetic frame creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 76,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-76.jpg",
    artist: "@mochrks",
    description: "Intimate portrait bringing the subject to life.",
    category: "photo",
  },
  {
    id: 77,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-77.jpg",
    artist: "@mochrks",
    description: "Striking snapshot captured during the golden hour.",
    category: "photo",
  },
  {
    id: 78,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-78.jpg",
    artist: "@mochrks",
    description: "Expressive photo capturing true personality.",
    category: "photo",
  },
  {
    id: 79,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-79.jpg",
    artist: "@mochrks",
    description: "Dramatic landscape freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 80,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-80.jpg",
    artist: "@mochrks",
    description: "Breathtaking photo telling a unique story.",
    category: "photo",
  },
  {
    id: 81,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-81.jpg",
    artist: "@mochrks",
    description: "Candid visual highlighting natural light.",
    category: "photo",
  },
  {
    id: 82,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-82.jpg",
    artist: "@mochrks",
    description: "Picturesque perspective evoking strong emotions.",
    category: "photo",
  },
  {
    id: 83,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-83.jpg",
    artist: "@mochrks",
    description: "Serene panorama telling a unique story.",
    category: "photo",
  },
  {
    id: 84,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-84.jpg",
    artist: "@mochrks",
    description: "Serene snapshot freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 85,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-85.jpg",
    artist: "@mochrks",
    description: "Vibrant macro shot revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 86,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-86.jpg",
    artist: "@mochrks",
    description: "Majestic photograph highlighting natural light.",
    category: "photo",
  },
  {
    id: 87,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-87.jpg",
    artist: "@mochrks",
    description: "Authentic image documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 88,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-88.jpg",
    artist: "@mochrks",
    description: "Dramatic frame revealing hidden details.",
    category: "photo",
  },
  {
    id: 89,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-89.jpg",
    artist: "@mochrks",
    description: "Evocative frame documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 90,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-90.jpg",
    artist: "@mochrks",
    description: "Artistic photo exploring leading lines.",
    category: "photo",
  },
  {
    id: 91,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-91.jpg",
    artist: "@mochrks",
    description: "Energetic frame revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 92,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-92.jpg",
    artist: "@mochrks",
    description: "Dramatic macro shot evoking strong emotions.",
    category: "photo",
  },
  {
    id: 93,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-93.jpg",
    artist: "@mochrks",
    description: "Candid snapshot revealing hidden details.",
    category: "photo",
  },
  {
    id: 94,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-94.jpg",
    artist: "@mochrks",
    description: "Poignant moment showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 95,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-95.jpg",
    artist: "@mochrks",
    description: "Authentic moment telling a unique story.",
    category: "photo",
  },
  {
    id: 96,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-96.jpg",
    artist: "@mochrks",
    description: "Energetic street photography capturing true personality.",
    category: "photo",
  },
  {
    id: 97,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-97.jpg",
    artist: "@mochrks",
    description: "Beautifully composed portrait revealing hidden details.",
    category: "photo",
  },
  {
    id: 98,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-98.jpg",
    artist: "@mochrks",
    description: "Picturesque exposure capturing true personality.",
    category: "photo",
  },
  {
    id: 99,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-99.jpg",
    artist: "@mochrks",
    description: "Intimate composition telling a unique story.",
    category: "photo",
  },
  {
    id: 100,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-100.jpg",
    artist: "@mochrks",
    description: "Timeless landscape showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 101,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-101.jpg",
    artist: "@mochrks",
    description: "Expressive macro shot exploring leading lines.",
    category: "photo",
  },
  {
    id: 102,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-102.jpg",
    artist: "@mochrks",
    description: "Powerful street photography revealing hidden details.",
    category: "photo",
  },
  {
    id: 103,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-103.jpg",
    artist: "@mochrks",
    description: "Beautifully composed street photography creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 104,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-104.jpg",
    artist: "@mochrks",
    description: "Poignant composition playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 105,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-105.jpg",
    artist: "@mochrks",
    description: "Vibrant visual playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 106,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-106.jpg",
    artist: "@mochrks",
    description: "Stunning scene revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 107,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-107.jpg",
    artist: "@mochrks",
    description: "Striking frame revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 108,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-108.jpg",
    artist: "@mochrks",
    description: "Nostalgic street photography highlighting natural light.",
    category: "photo",
  },
  {
    id: 109,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-109.jpg",
    artist: "@mochrks",
    description: "Majestic exposure exploring leading lines.",
    category: "photo",
  },
  {
    id: 110,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-110.jpg",
    artist: "@mochrks",
    description: "Vivid portrait highlighting natural light.",
    category: "photo",
  },
  {
    id: 111,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-111.jpg",
    artist: "@mochrks",
    description: "Captivating perspective showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 112,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-112.jpg",
    artist: "@mochrks",
    description: "Majestic exposure documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 113,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-113.jpg",
    artist: "@mochrks",
    description: "Authentic photograph revealing hidden details.",
    category: "photo",
  },
  {
    id: 114,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-114.jpg",
    artist: "@mochrks",
    description: "Powerful photographic shot creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 115,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-115.jpg",
    artist: "@mochrks",
    description: "Captivating image captured during the golden hour.",
    category: "photo",
  },
  {
    id: 116,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-116.jpg",
    artist: "@mochrks",
    description: "Majestic macro shot captured during the golden hour.",
    category: "photo",
  },
  {
    id: 117,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-117.jpg",
    artist: "@mochrks",
    description: "Beautifully composed scene showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 118,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-118.jpg",
    artist: "@mochrks",
    description: "Raw capture playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 119,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-119.jpg",
    artist: "@mochrks",
    description: "Authentic image freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 120,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-120.jpg",
    artist: "@mochrks",
    description: "Dramatic photo highlighting natural light.",
    category: "photo",
  },
  {
    id: 121,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-121.jpg",
    artist: "@mochrks",
    description: "Poignant image bringing the subject to life.",
    category: "photo",
  },
  {
    id: 122,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-122.jpg",
    artist: "@mochrks",
    description: "Mesmerizing photographic shot telling a unique story.",
    category: "photo",
  },
  {
    id: 123,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-123.jpg",
    artist: "@mochrks",
    description: "Beautifully composed image telling a unique story.",
    category: "photo",
  },
  {
    id: 124,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-124.jpg",
    artist: "@mochrks",
    description: "Timeless exposure freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 125,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-125.jpg",
    artist: "@mochrks",
    description: "Candid panorama documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 126,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-126.jpg",
    artist: "@mochrks",
    description: "Captivating visual documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 127,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-127.jpg",
    artist: "@mochrks",
    description: "Majestic photo telling a unique story.",
    category: "photo",
  },
  {
    id: 128,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-128.jpg",
    artist: "@mochrks",
    description: "Energetic photo focusing on symmetry.",
    category: "photo",
  },
  {
    id: 129,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-129.jpg",
    artist: "@mochrks",
    description: "Striking photographic shot focusing on symmetry.",
    category: "photo",
  },
  {
    id: 130,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-130.jpg",
    artist: "@mochrks",
    description: "Expressive macro shot showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 131,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-131.jpg",
    artist: "@mochrks",
    description: "Timeless landscape revealing hidden details.",
    category: "photo",
  },
  {
    id: 132,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-132.jpg",
    artist: "@mochrks",
    description: "Energetic photographic shot documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 133,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-133.jpg",
    artist: "@mochrks",
    description: "Timeless photo telling a unique story.",
    category: "photo",
  },
  {
    id: 134,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-134.jpg",
    artist: "@mochrks",
    description: "Poignant capture revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 135,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-135.jpg",
    artist: "@mochrks",
    description: "Stunning portrait showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 136,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-136.jpg",
    artist: "@mochrks",
    description: "Candid macro shot documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 137,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-137.jpg",
    artist: "@mochrks",
    description: "Energetic composition showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 138,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-138.jpg",
    artist: "@mochrks",
    description: "Evocative moment revealing hidden details.",
    category: "photo",
  },
  {
    id: 139,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-139.jpg",
    artist: "@mochrks",
    description: "Picturesque photo revealing hidden details.",
    category: "photo",
  },
  {
    id: 140,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-140.jpg",
    artist: "@mochrks",
    description: "Evocative scene freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 141,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-141.jpg",
    artist: "@mochrks",
    description: "Picturesque landscape creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 142,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-142.jpg",
    artist: "@mochrks",
    description: "Majestic moment capturing true personality.",
    category: "photo",
  },
  {
    id: 143,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-143.jpg",
    artist: "@mochrks",
    description: "Breathtaking image evoking strong emotions.",
    category: "photo",
  },
  {
    id: 144,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-144.jpg",
    artist: "@mochrks",
    description: "Expressive landscape exploring leading lines.",
    category: "photo",
  },
  {
    id: 145,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-145.jpg",
    artist: "@mochrks",
    description: "Raw snapshot freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 146,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-146.jpg",
    artist: "@mochrks",
    description: "Beautifully composed exposure bringing the subject to life.",
    category: "photo",
  },
  {
    id: 147,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-147.jpg",
    artist: "@mochrks",
    description: "Dramatic scene showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 148,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-148.jpg",
    artist: "@mochrks",
    description: "Picturesque photographic shot bringing the subject to life.",
    category: "photo",
  },
  {
    id: 149,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-149.jpg",
    artist: "@mochrks",
    description: "Ethereal photo bringing the subject to life.",
    category: "photo",
  },
  {
    id: 150,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-150.jpg",
    artist: "@mochrks",
    description: "Energetic panorama capturing true personality.",
    category: "photo",
  },
  {
    id: 151,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-151.jpg",
    artist: "@mochrks",
    description: "Breathtaking frame telling a unique story.",
    category: "photo",
  },
  {
    id: 152,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-152.jpg",
    artist: "@mochrks",
    description: "Mesmerizing exposure exploring leading lines.",
    category: "photo",
  },
  {
    id: 153,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-153.jpg",
    artist: "@mochrks",
    description: "Authentic perspective documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 154,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-154.jpg",
    artist: "@mochrks",
    description: "Authentic capture bringing the subject to life.",
    category: "photo",
  },
  {
    id: 155,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-155.jpg",
    artist: "@mochrks",
    description: "Candid landscape bringing the subject to life.",
    category: "photo",
  },
  {
    id: 156,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/instagram/ig-156.jpg",
    artist: "@mochrks",
    description: "Captivating panorama revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 157,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-1.jpg",
    artist: "@mochrks",
    description: "Candid street photography capturing true personality.",
    category: "photo",
  },
  {
    id: 158,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-10.jpg",
    artist: "@mochrks",
    description: "Energetic photograph highlighting natural light.",
    category: "photo",
  },
  {
    id: 159,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-11.jpg",
    artist: "@mochrks",
    description: "Evocative perspective playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 160,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-12.jpg",
    artist: "@mochrks",
    description: "Ethereal macro shot documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 161,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-13.jpg",
    artist: "@mochrks",
    description: "Vibrant scene freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 162,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-14.jpg",
    artist: "@mochrks",
    description: "Nostalgic frame showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 163,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-15.jpg",
    artist: "@mochrks",
    description: "Poignant portrait captured during the golden hour.",
    category: "photo",
  },
  {
    id: 164,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-16.jpg",
    artist: "@mochrks",
    description: "Breathtaking image telling a unique story.",
    category: "photo",
  },
  {
    id: 165,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-17.jpg",
    artist: "@mochrks",
    description: "Cinematic photograph freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 166,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-18.jpg",
    artist: "@mochrks",
    description: "Timeless photo creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 167,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-19.jpg",
    artist: "@mochrks",
    description: "Majestic moment focusing on symmetry.",
    category: "photo",
  },
  {
    id: 168,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-2.jpg",
    artist: "@mochrks",
    description: "Expressive visual bringing the subject to life.",
    category: "photo",
  },
  {
    id: 169,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-20.jpg",
    artist: "@mochrks",
    description: "Authentic frame telling a unique story.",
    category: "photo",
  },
  {
    id: 170,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-21.jpg",
    artist: "@mochrks",
    description: "Captivating visual creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 171,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-22.jpg",
    artist: "@mochrks",
    description: "Nostalgic capture telling a unique story.",
    category: "photo",
  },
  {
    id: 172,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-23.jpg",
    artist: "@mochrks",
    description: "Intimate panorama revealing hidden details.",
    category: "photo",
  },
  {
    id: 173,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-24.jpg",
    artist: "@mochrks",
    description: "Picturesque macro shot preserving memories.",
    category: "photo",
  },
  {
    id: 174,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-25.jpg",
    artist: "@mochrks",
    description: "Beautifully composed photographic shot creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 175,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-26.jpg",
    artist: "@mochrks",
    description: "Cinematic landscape capturing true personality.",
    category: "photo",
  },
  {
    id: 176,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-27.jpg",
    artist: "@mochrks",
    description: "Vivid portrait captured during the golden hour.",
    category: "photo",
  },
  {
    id: 177,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-28.jpg",
    artist: "@mochrks",
    description: "Stunning moment documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 178,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-29.jpg",
    artist: "@mochrks",
    description: "Cinematic macro shot focusing on symmetry.",
    category: "photo",
  },
  {
    id: 179,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-3.jpg",
    artist: "@mochrks",
    description: "Picturesque photograph telling a unique story.",
    category: "photo",
  },
  {
    id: 180,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-30.jpg",
    artist: "@mochrks",
    description: "Cinematic image revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 181,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-31.jpg",
    artist: "@mochrks",
    description: "Dramatic photograph telling a unique story.",
    category: "photo",
  },
  {
    id: 182,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-32.jpg",
    artist: "@mochrks",
    description: "Nostalgic landscape telling a unique story.",
    category: "photo",
  },
  {
    id: 183,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-33.jpg",
    artist: "@mochrks",
    description: "Picturesque image evoking strong emotions.",
    category: "photo",
  },
  {
    id: 184,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-34.jpg",
    artist: "@mochrks",
    description: "Breathtaking photograph exploring leading lines.",
    category: "photo",
  },
  {
    id: 185,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-35.jpg",
    artist: "@mochrks",
    description: "Striking frame exploring leading lines.",
    category: "photo",
  },
  {
    id: 186,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-36.jpg",
    artist: "@mochrks",
    description: "Nostalgic landscape preserving memories.",
    category: "photo",
  },
  {
    id: 187,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-37.jpeg",
    artist: "@mochrks",
    description: "Cinematic portrait preserving memories.",
    category: "photo",
  },
  {
    id: 188,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-38.jpg",
    artist: "@mochrks",
    description: "Beautifully composed photo telling a unique story.",
    category: "photo",
  },
  {
    id: 189,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-39.jpeg",
    artist: "@mochrks",
    description: "Cinematic snapshot highlighting natural light.",
    category: "photo",
  },
  {
    id: 190,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-4.jpg",
    artist: "@mochrks",
    description: "Powerful photograph creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 191,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-40.png",
    artist: "@mochrks",
    description: "Vivid exposure playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 192,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-41.png",
    artist: "@mochrks",
    description: "Authentic moment creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 193,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-42.png",
    artist: "@mochrks",
    description: "Dramatic image creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 194,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-43.jpeg",
    artist: "@mochrks",
    description: "Candid photograph capturing true personality.",
    category: "photo",
  },
  {
    id: 195,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-44.png",
    artist: "@mochrks",
    description: "Artistic perspective focusing on symmetry.",
    category: "photo",
  },
  {
    id: 196,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-45.png",
    artist: "@mochrks",
    description: "Stunning composition exploring leading lines.",
    category: "photo",
  },
  {
    id: 197,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-46.png",
    artist: "@mochrks",
    description: "Intimate photographic shot highlighting natural light.",
    category: "photo",
  },
  {
    id: 198,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-47.jpg",
    artist: "@mochrks",
    description: "Captivating photographic shot capturing true personality.",
    category: "photo",
  },
  {
    id: 199,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-48.png",
    artist: "@mochrks",
    description: "Stunning image playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 200,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-49.jpg",
    artist: "@mochrks",
    description: "Dramatic photo playing with shadows and contrast.",
    category: "photo",
  },
  {
    id: 201,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-5.jpg",
    artist: "@mochrks",
    description: "Intimate visual creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 202,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-50.png",
    artist: "@mochrks",
    description: "Cinematic photograph preserving memories.",
    category: "photo",
  },
  {
    id: 203,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-51.png",
    artist: "@mochrks",
    description: "Stunning photo focusing on symmetry.",
    category: "photo",
  },
  {
    id: 204,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-52.png",
    artist: "@mochrks",
    description: "Moody composition highlighting natural light.",
    category: "photo",
  },
  {
    id: 205,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-53.jpg",
    artist: "@mochrks",
    description: "Candid exposure freezing a perfect moment.",
    category: "photo",
  },
  {
    id: 206,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-54.jpg",
    artist: "@mochrks",
    description: "Picturesque visual showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 207,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-55.jpeg",
    artist: "@mochrks",
    description: "Dramatic composition showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 208,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-56.jpeg",
    artist: "@mochrks",
    description: "Raw photograph revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 209,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-57.png",
    artist: "@mochrks",
    description: "Captivating panorama revealing hidden details.",
    category: "photo",
  },
  {
    id: 210,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-58.jpeg",
    artist: "@mochrks",
    description: "Poignant composition showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 211,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-59.jpeg",
    artist: "@mochrks",
    description: "Intimate portrait preserving memories.",
    category: "photo",
  },
  {
    id: 212,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-6.jpg",
    artist: "@mochrks",
    description: "Majestic perspective captured during the golden hour.",
    category: "photo",
  },
  {
    id: 213,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-60.jpeg",
    artist: "@mochrks",
    description: "Serene panorama showcasing the beauty of nature.",
    category: "photo",
  },
  {
    id: 214,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-61.jpeg",
    artist: "@mochrks",
    description: "Expressive moment documenting a fleeting second.",
    category: "photo",
  },
  {
    id: 215,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-62.jpeg",
    artist: "@mochrks",
    description: "Energetic composition preserving memories.",
    category: "photo",
  },
  {
    id: 216,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-63.jpeg",
    artist: "@mochrks",
    description: "Captivating capture creating a cinematic atmosphere.",
    category: "photo",
  },
  {
    id: 217,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-7.jpg",
    artist: "@mochrks",
    description: "Stunning street photography revealing hidden details.",
    category: "photo",
  },
  {
    id: 218,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-8.jpg",
    artist: "@mochrks",
    description: "Artistic moment revealing the essence of city life.",
    category: "photo",
  },
  {
    id: 219,
    title: "Photography",
    imageUrl: "https://mochrks.github.io/assets/photos/photo-9.jpg",
    artist: "@mochrks",
    description: "Picturesque exposure evoking strong emotions.",
    category: "photo",
  },
];
